config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  # Go to home/index by default
  root 'home#index'
  # About page
  get '/about' => 'home#about'

end

app/models/answer.rb
class Answer < ApplicationRecord

    include HasGravatar

    belongs_to :question    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar
    def gravatar
        "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}/?d=robohash"
    end
end

app/models/question.rb
class Question < ApplicationRecord
    include HasGravatar

    has_many :answers

    validates :email, length: { minimum: 5 }
    validates :body, length: { minimum: 1 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def create
        question = Question.find(params[:answer][:question_id])
        Answer.create(answer_params)
        redirect_to question
    end

    private
    def answer_params
        params.require(:answer).permit(:question_id, :email, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end
  def about
  end
  def temp
    redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def index
        redirect_to root_path
    end
    
    def show
        @question = Question.find(params[:id])

        @answers = @question.answers.order(created_at: :desc)
    end

    def create
        @question = Question.new(question_params)
        if @question.valid? 
            @question.save
            redirect_to Question.last 
        end
 end
 

    private
    def question_params
        params.require(:question).permit(:email, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CA Brisbane Forum</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><form><a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask Question</a></form></li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Provide an answer</h4>
      </div>
      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
      <input type="hidden" name="answer[question_id]" value="<%=@question.id %>">
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="answer[email]" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Answer</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="answer[body]" id="inputQuestion" placeholder="What is your answer?" required></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="Submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Ask a question</h4>
      </div>
      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
        <div class="modal-body">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" name="question[email]" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="question[body]" id="inputQuestion" placeholder="What would you like to know" required></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="Submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>About</h1>
<p>This forum is used to ask questions of the CA Brisbane cohort</p>

app/views/home/index.html.erb
<h1>CA Brisbane Forum</h1>
<p>Welcome to the Brisbane Coder Academy Forum</p>

<%# media from bootstrap %>
<% @questions.each do |q| %>


<div class="media">
    <div class="media-left media-middle">
        <a href="#">
        <img class="media-object" src=<%=q.gravatar%> >
        </a>
    </div>
    <div class="media-body">
        <h4 class="media-heading"><%=q.email%> asked:</h4>
        <div><%=time_ago_in_words q.created_at%> ago:</div>
        <%=q.body%>
    <div>
        <a href="<%= question_path(q) %>" class="btn btn-success btn-xs">View Answers</a>
    </div>    
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CA Brisbane Forum</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%# Use bootstrap %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%# from bootstrap %>
  <div class="container">
    <%= render 'home/navbar' %>
    <%= yield %>
    <%= render 'home/new_question_form'%>
  </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.email %></td>
        <td><%= question.body %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="lead well">
    <div class="media">
        <div class="media-left media-middle">
            <a href="#">
            <img class="media-object" src=<%=@question.gravatar%> >
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading"><%=@question.email%> asked:</h4>
            <%=@question.body%>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <div>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
        </div>
        <%# render the answer model%>
        <%=render 'home/new_answer_form'%>

        <% for answer in @answers do %>
            <div class="media">
                <div class="media-left media-middle">
                    <a href="#">
                    <img class="media-object" src="<%= answer.gravatar %>" >
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading"><%= answer.email %> answered:</h4>
                    <div><%=time_ago_in_words answer.created_at%> ago:</div>
                    <%= answer.body %>
                </div>
            </div>
        <% end %>

    </div>
</div>